service: fipefacil
app: fipefacil
org: thalesfp

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /check
          method: get
