service: fipefacil
app: fipefacil
org: thalesfp

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  memorySize: 512
  # cfnRole: arn:aws:iam:678634121400:role/role
  environment:
    TABLE_NAME: fipe
    BRANDS_QUEUE: https://sqs.${self:provider.region}.amazonaws.com/678634121400/brands
    REFERENCES_QUEUE: https://sqs.${self:provider.region}.amazonaws.com/678634121400/references
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:678634121400:table/fipe
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
      Resource:
        - arn:aws:sqs:${self:provider.region}:678634121400:brands
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
      Resource:
        - arn:aws:sqs:${self:provider.region}:678634121400:references

functions:
  checkForUpdate:
    handler: src/lambda/handler.checkForUpdateHandler
    events:
      - http:
          path: /checkForUpdate
          method: get
  startUpdate:
    handler: src/lambda/handler.startUpdateHandler
    reservedConcurrency: 10
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:678634121400:references
          batchSize: 1
      - http:
          path: /startUpdate
          method: get

resources:
  Resources:
    FipeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: fipe
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ReferencesQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "references"
    BrandsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "brands"
