Resources:
  ReferencesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.queues.references.${self:provider.stage}}
  BrandsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.queues.brands.${self:provider.stage}}
  ModelsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.queues.models.${self:provider.stage}}
  YearModelsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.queues.yearModels.${self:provider.stage}}
