Resources:
  UpdateFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: update-files-bucket-${self:provider.stage}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000
