Resources:
  ReferencesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: references-${self:provider.stage}
  BrandsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: brands-${self:provider.stage}
  ModelsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: models-${self:provider.stage}
  YearModelsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: yearmodels-${self:provider.stage}
