name: branch master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run Docker Compose
        run: docker-compose up -d
      - name: Run Unit Tests
        run: npm run test:unit
        env:
          CI: true
      - name: Run Services Tests
        run: npm run test:services
      - name: Run Integration Tests
        run: npm run test:integration
        env:
          CI: true
          AWS_REGION: us-east-1
          AWS_DYNAMODB_ENDPOINT: http://localhost:8000
          AWS_SQS_ENDPOINT: http://localhost:9324
          REFERENCES_QUEUE: http://localhost:9324/queue/references
          BRANDS_QUEUE: http://localhost:9324/queue/brands
          MODELS_QUEUE: http://localhost:9324/queue/models
          YEAR_MODELS_QUEUE: http://localhost:9324/queue/yearmodels
          PRICES_TABLE: prices_test
          AWS_S3_ENDPOINT: http://localhost:9000
          UPDATE_FILES_BUCKET_NAME: file-updates-bucket
          UPDATE_FILES_BUCKET_REGION: sa-east-1
          AWS_ACCESS_KEY_ID: minio_access_key
          AWS_SECRET_ACCESS_KEY: minio_secret_key
      - name: serverless deploy
        run: npm run deploy:production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
