name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run Unit Tests 
      run: npm run test:unit
      env:
        CI: true
    - name: Run Docker Compose
      run: docker-compose up
    - name: Run Integration Tests
      run: npm run test:integration
      env:
        CI: true
