name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Run Unit Tests 
      run: npm run test:unit
      env:
        CI: true
    - name: Run Docker Compose
      run: docker-compose up -d
    - name: Run Integration Tests
      run: npm run test:integration
      env:
        CI: true
        AWS_ACCESS_KEY_ID: foobar
        AWS_SECRET_ACCESS_KEY: foobar
        AWS_REGION: us-east-1
        AWS_DYNAMODB_ENDPOINT: http://localhost:4569
        AWS_SQS_ENDPOINT: http://localhost:4576
        REFERENCES_QUEUE: http://localhost:4576/queue/references
        TABLE_NAME: fipe_test
